[package]
name = "client"
version = "0.1.0"
authors = ["Amer Safdari <safda004@umn.edu>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
derive_more = "0.13"
log = { version = "0.4", features = ["std"] }
wee_alloc = "0.4"

events = {path = "../events"}
