[package]
name = "nidaqmx"
version = "0.1.0"
authors = ["Amer Safdari <amersafdari@gmail.com>"]
edition = "2018"

[dependencies]
nidaqmx-sys = {path = "../nidaqmx-sys"}

time = "^0.1"
futures = "^0.1"
winapi = { version = "0.3", features = ["winuser","impl-default"] }
