[package]
name = "nidaqmx"
version = "0.1.0"
authors = ["Amer Safdari <safda004@umn.edu>"]
edition = "2018"

[dependencies]
nidaqmx-sys = {path = "../nidaqmx-sys"}

time = "0.1"
futures-preview = "0.3.0-alpha.12"
