[package]
name = "scissors_console"
version = "0.2.0"
authors = ["Amer Safdari <safda004@umn.edu>"]
edition = "2018"

[dependencies]
nidaqmx = {path = "../nidaqmx"}

tether = "0.2"
log = "0.4"
nfd = "0.0.4"
time = "0.1"

futures-preview = "0.3.0-alpha.12"
