[package]
name = "nativefiledialog-rs"
version = "0.1.0"
authors = ["Amer Safdari <amersafdari@gmail.com>"]
edition = "2018"

license = "MIT"

[dependencies]
nativefiledialog-sys = { path = "../nativefiledialog-sys" }
